"""
phase3/train_config.py

Generates all YOLO training config files for a 24GB VRAM instance:
  - data.yaml          (already written by phase 1)
  - hyp_weapon.yaml    (hyperparameters tuned for weapon detection)
  - augmentation notes (Albumentations config embedded in training call)

Model: YOLOv11x (largest, best mAP)
Input size: 1280px (critical for small weapons in CCTV)
Batch: 8 with AMP (fits 24GB at 1280px)

Key decisions vs default YOLO settings:
  - Higher mosaic probability (weapons need context)
  - More aggressive copy-paste (rare weapon appearances)
  - Custom Albumentations for CCTV realism
  - Cosine LR with warm restarts
  - No mosaic for last 15 epochs (fine-tune on clean images)
  - Label smoothing 0.1 (reduces overconfidence)
  - Close mosaic at epoch 85/100 (stabilize final convergence)
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from data.utils import log, BASE_OUT

PHASE3_DIR = Path(__file__).parent
RUNS_DIR   = Path("/data/runs")


def write_hyperparams():
    """Write the hyperparameter YAML for weapon detection."""
    hyp = {
        # ── Learning rate ────────────────────────────────────────────────────
        "lr0":         0.01,      # Initial LR (cosine schedule)
        "lrf":         0.01,      # Final LR = lr0 * lrf
        "momentum":    0.937,
        "weight_decay": 0.0005,
        "warmup_epochs": 3.0,
        "warmup_momentum": 0.8,
        "warmup_bias_lr": 0.1,

        # ── Loss weights ─────────────────────────────────────────────────────
        "box":   7.5,    # Box regression loss weight (higher = more precise boxes)
        "cls":   0.5,    # Class loss weight (low — only 1 class)
        "dfl":   1.5,    # Distribution focal loss

        # ── Augmentation ─────────────────────────────────────────────────────
        # These are YOLO's built-in mosaic/affine params:
        "hsv_h":   0.015,   # Hue jitter
        "hsv_s":   0.7,     # Saturation jitter
        "hsv_v":   0.4,     # Value/brightness jitter (↑ for low-light CCTV)
        "degrees":  5.0,    # Rotation (small — CCTV mostly static)
        "translate": 0.1,   # Translation
        "scale":    0.6,    # Scale jitter (↑ to handle small weapons)
        "shear":    2.0,    # Shear
        "perspective": 0.0002,  # Perspective (small for CCTV)
        "flipud":   0.0,    # No vertical flip (cameras don't invert)
        "fliplr":   0.5,    # Horizontal flip OK
        "bgr":      0.0,
        "mosaic":   1.0,    # Full mosaic (essential for small object detection)
        "mixup":    0.15,   # MixUp augmentation
        "copy_paste": 0.3,  # Copy-paste (pastes weapon boxes onto negatives — CRITICAL)
        "copy_paste_mode": "flip",
        "auto_augment": "randaugment",
        "erasing":  0.4,    # Random erasing (simulates occlusion)
        "crop_fraction": 1.0,

        # ── Label smoothing ──────────────────────────────────────────────────
        "label_smoothing": 0.1,  # Reduces overconfidence → better calibration
        "nbs":      64,     # Nominal batch size for LR scaling
    }

    hyp_path = PHASE3_DIR / "hyp_weapon.yaml"
    lines = ["# Weapon Detection Hyperparameters — YOLOv11x @ 1280px", "# Generated by train_config.py", ""]
    for k, v in hyp.items():
        lines.append(f"{k}: {v}")

    hyp_path.write_text("\n".join(lines))
    log.info(f"  Written: {hyp_path}")
    return hyp_path


def write_albumentations_config():
    """
    Write Albumentations config for CCTV-realistic augmentations.
    YOLO supports custom albumentations via a JSON config passed to --albu.
    These augmentations simulate real CCTV degradation that standard YOLO
    augmentation doesn't cover.
    """
    config = {
        "transform": {
            "__class_fullname__": "Compose",
            "bbox_params": {
                "__class_fullname__": "BboxParams",
                "format": "yolo",
                "label_fields": ["class_labels"],
                "min_visibility": 0.3,
            },
            "transforms": [
                # CCTV compression artifacts
                {
                    "__class_fullname__": "ImageCompression",
                    "quality_lower": 30,
                    "quality_upper": 75,
                    "p": 0.5,
                },
                # Motion blur (PTZ camera movement, fast action)
                {
                    "__class_fullname__": "MotionBlur",
                    "blur_limit": [3, 9],
                    "p": 0.4,
                },
                # Low light / night CCTV simulation
                {
                    "__class_fullname__": "RandomBrightnessContrast",
                    "brightness_limit": [-0.4, 0.2],
                    "contrast_limit":   [-0.3, 0.3],
                    "p": 0.6,
                },
                # Sensor noise (especially in low-light CCTV)
                {
                    "__class_fullname__": "GaussNoise",
                    "var_limit": [10.0, 80.0],
                    "p": 0.4,
                },
                # Grayscale (many CCTV cameras are monochrome)
                {
                    "__class_fullname__": "ToGray",
                    "p": 0.2,
                },
                # Simulate low-res / old camera upscale
                {
                    "__class_fullname__": "Downscale",
                    "scale_min": 0.5,
                    "scale_max": 0.75,
                    "p": 0.25,
                },
                # Rain / weather (outdoor CCTV)
                {
                    "__class_fullname__": "RandomRain",
                    "slant_lower": -10,
                    "slant_upper":  10,
                    "drop_length": 10,
                    "drop_width":   1,
                    "drop_color": [200, 200, 200],
                    "blur_value":   2,
                    "brightness_coefficient": 0.9,
                    "rain_type": "default",
                    "p": 0.1,
                },
                # Partial occlusion (weapon partially behind person/object)
                {
                    "__class_fullname__": "CoarseDropout",
                    "max_holes":     8,
                    "max_height":   32,
                    "max_width":    32,
                    "min_holes":     1,
                    "fill_value":    0,
                    "p": 0.3,
                },
            ],
        }
    }

    import json
    cfg_path = PHASE3_DIR / "albumentations_cctv.json"
    cfg_path.write_text(json.dumps(config, indent=2))
    log.info(f"  Written: {cfg_path}")
    return cfg_path


def write_train_script(data_yaml: Path, hyp_yaml: Path, albu_json: Path):
    """Write the main training shell script."""
    script = f"""#!/bin/bash
# ============================================================
#  Weapon Detection — YOLOv11x Training Script
#  Phase 3, Run v1 (Baseline)
# ============================================================
set -e

DATA_YAML="{data_yaml}"
HYP_YAML="{hyp_yaml}"
ALBU_JSON="{albu_json}"
RUNS_DIR="{RUNS_DIR}"
PROJECT="weapon_detection"
RUN_NAME="v1_baseline"

echo "========================================"
echo "  Starting YOLOv11x training"
echo "  Data:  $DATA_YAML"
echo "  Runs:  $RUNS_DIR/$PROJECT/$RUN_NAME"
echo "========================================"

# Install/upgrade ultralytics if needed
pip install -q ultralytics>=8.3.0

python - <<'PYTHON'
from ultralytics import YOLO
import torch

print(f"PyTorch: {{torch.__version__}}")
print(f"CUDA:    {{torch.cuda.is_available()}}")
if torch.cuda.is_available():
    print(f"GPU:     {{torch.cuda.get_device_name(0)}}")
    print(f"VRAM:    {{torch.cuda.get_device_properties(0).total_memory / 1e9:.1f}} GB")

model = YOLO("yolo11x.pt")   # downloads pretrained weights automatically

results = model.train(
    data="{data_yaml}",
    epochs=100,
    imgsz=1280,

    # ── Batch & hardware ────────────────────────────────────────
    batch=8,                   # 8 × 1280px fits ~24GB with AMP
    workers=8,
    device=0,
    amp=True,                  # Automatic Mixed Precision (saves ~40% VRAM)
    cache="disk",              # Cache preprocessed images to disk (not RAM)

    # ── Optimizer ───────────────────────────────────────────────
    optimizer="AdamW",
    lr0=0.001,                 # Lower LR for AdamW vs SGD
    lrf=0.01,
    warmup_epochs=3,
    cos_lr=True,               # Cosine LR schedule

    # ── Augmentation ────────────────────────────────────────────
    mosaic=1.0,
    copy_paste=0.3,
    mixup=0.15,
    degrees=5.0,
    scale=0.6,
    fliplr=0.5,
    hsv_v=0.4,                 # More brightness variation for CCTV
    close_mosaic=15,           # Turn off mosaic last 15 epochs for fine-tuning

    # ── Regularization ──────────────────────────────────────────
    weight_decay=0.0005,
    label_smoothing=0.1,
    dropout=0.0,

    # ── Output ──────────────────────────────────────────────────
    project="{RUNS_DIR}/{{}}/".format("weapon_detection"),
    name="v1_baseline",
    save=True,
    save_period=10,            # Save checkpoint every 10 epochs
    val=True,
    plots=True,

    # ── Training stability ───────────────────────────────────────
    patience=30,               # Early stop if no improvement for 30 epochs
    exist_ok=False,
    verbose=True,

    # ── Loss weights ────────────────────────────────────────────
    box=7.5,
    cls=0.5,
    dfl=1.5,

    # ── Albumentations (CCTV augmentations) ─────────────────────
    # Uncomment if albumentations is installed:
    # albu_json="{albu_json}",
)

print("\\n✓ Training complete!")
print(f"Best model: {{results.save_dir}}/weights/best.pt")
print(f"mAP50:      {{results.results_dict.get('metrics/mAP50(B)', 'N/A')}}")
print(f"mAP50-95:   {{results.results_dict.get('metrics/mAP50-95(B)', 'N/A')}}")
PYTHON

echo ""
echo "Training complete. Run v1 results in: $RUNS_DIR/weapon_detection/v1_baseline/"
echo "Next: python phase3/hard_negative_mining.py"
"""

    script_path = PHASE3_DIR / "train_v1_baseline.sh"
    script_path.write_text(script)
    script_path.chmod(0o755)
    log.info(f"  Written: {script_path}")
    return script_path


def write_train_v2_script(data_yaml: Path):
    """Script for v2 training after hard negative mining."""
    script = f"""#!/bin/bash
# ============================================================
#  Weapon Detection — YOLOv11x Training v2
#  Resume/retrain AFTER hard negative mining
#  Uses best.pt from v1 as starting weights
# ============================================================
set -e

RUNS_DIR="{RUNS_DIR}"
V1_WEIGHTS="$RUNS_DIR/weapon_detection/v1_baseline/weights/best.pt"
DATA_YAML="{data_yaml}"

if [ ! -f "$V1_WEIGHTS" ]; then
    echo "ERROR: v1 weights not found at $V1_WEIGHTS"
    echo "Run train_v1_baseline.sh first."
    exit 1
fi

echo "Starting v2 training with hard-negative-augmented dataset..."
echo "Base weights: $V1_WEIGHTS"

python - <<'PYTHON'
from ultralytics import YOLO

# Load best weights from v1
model = YOLO("{RUNS_DIR}/weapon_detection/v1_baseline/weights/best.pt")

results = model.train(
    data="{data_yaml}",
    epochs=50,               # Fewer epochs — already pretrained
    imgsz=1280,
    batch=8,
    workers=8,
    device=0,
    amp=True,
    cache="disk",

    optimizer="AdamW",
    lr0=0.0001,              # 10× lower LR — fine-tuning, not training from scratch
    lrf=0.01,
    cos_lr=True,
    warmup_epochs=1,

    # Slightly reduced augmentation for fine-tuning
    mosaic=0.8,
    copy_paste=0.2,
    mixup=0.05,
    close_mosaic=10,

    weight_decay=0.0005,
    label_smoothing=0.05,    # Reduced label smoothing for fine-tuning

    project="{RUNS_DIR}/weapon_detection",
    name="v2_hardneg",
    save=True,
    save_period=5,
    val=True,
    plots=True,
    patience=20,

    box=7.5,
    cls=0.5,
    dfl=1.5,
)

print("\\n✓ v2 training complete!")
print(f"Best model: {{results.save_dir}}/weights/best.pt")
print(f"mAP50:      {{results.results_dict.get('metrics/mAP50(B)', 'N/A')}}")
print(f"mAP50-95:   {{results.results_dict.get('metrics/mAP50-95(B)', 'N/A')}}")
PYTHON
"""

    script_path = PHASE3_DIR / "train_v2_hardneg.sh"
    script_path.write_text(script)
    script_path.chmod(0o755)
    log.info(f"  Written: {script_path}")
    return script_path


def main():
    log.info("Generating Phase 3 training config files...")
    PHASE3_DIR.mkdir(parents=True, exist_ok=True)
    RUNS_DIR.mkdir(parents=True, exist_ok=True)

    data_yaml = BASE_OUT / "data.yaml"
    hyp_yaml  = write_hyperparams()
    albu_json = write_albumentations_config()

    write_train_script(data_yaml, hyp_yaml, albu_json)
    write_train_v2_script(data_yaml)

    log.info("\nAll config files written:")
    for f in sorted(PHASE3_DIR.glob("*")):
        if f.is_file():
            log.info(f"  {f}")


if __name__ == "__main__":
    main()
